### ISSUE TITLE
Requests the pdf file which has not been generated

### ISSUE THREAD

**Issue by rutvora** [PranjalGupta2199/TimeTable-BPHC#1]
On the initial load, it requests path to a pdf file which it has to generate itself

Suggestion: Change the guide text mentioning which PDF they have to select

**Comment by rutvora** [comment]
Also, giving it a random PDF (obtained for the internet) creates 2 errors
1. GTK's "is a File" check fails for some reason
2. EOF not found by PyPDF2.utils

**Comment by PranjalGupta2199** [comment]
Is this okay ?
![issue page](https://user-images.githubusercontent.com/31805699/43277660-53dcf7c2-9126-11e8-850b-06d576dd0205.png)

**Comment by rutvora** [comment]
cool
